### ISSUE TITLE
Couldn't use with glimmer-dsl-swt

### ISSUE THREAD

**Issue by phuongnd08** [AndyObtiva/glimmer-cw-video#11] opened 2023-06-11 00:49 UTC
My Gemfile:

```
gem 'matrix'
gem 'glimmer-dsl-swt'
gem 'glimmer-cw-video'
```

(I have expliticitly declare matrix - somehow not declared as dependencies of glimmer-cw-video)

Here is the code I tried to run
```
require 'glimmer-dsl-swt'
require 'glimmer-cw-video'

include Glimmer
    shell {
      text 'Hello, Video!'
      minimum_size 384, 240
      video
    }.open

```

Result:

```
[2023-06-11 07:46:39] ERROR glimmer: /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-xml-1.3.1/lib/glimmer/xml/xml_visitor.rb:83:in `block in append_attributes': undefined method `xml_attribute_underscore' for Glimmer::Config:Module (NoMethodError)
	from org/jruby/RubyHash.java:1587:in `each'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-xml-1.3.1/lib/glimmer/xml/xml_visitor.rb:80:in `append_attributes'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-xml-1.3.1/lib/glimmer/xml/html_visitor.rb:57:in `append_attributes'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-xml-1.3.1/lib/glimmer/xml/xml_visitor.rb:41:in `process_before_children'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-xml-1.3.1/lib/glimmer/xml/depth_first_search_iterator.rb:37:in `process'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-xml-1.3.1/lib/glimmer/xml/depth_first_search_iterator.rb:38:in `block in process'
	from org/jruby/RubyArray.java:1987:in `each'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-xml-1.3.1/lib/glimmer/xml/depth_first_search_iterator.rb:38:in `process'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-xml-1.3.1/lib/glimmer/xml/depth_first_search_iterator.rb:38:in `block in process'
	from org/jruby/RubyArray.java:1987:in `each'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-xml-1.3.1/lib/glimmer/xml/depth_first_search_iterator.rb:38:in `process'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-xml-1.3.1/lib/glimmer/xml/depth_first_search_iterator.rb:33:in `iterate'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-xml-1.3.1/lib/glimmer/xml/html_node.rb:32:in `to_xml'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.21.2.1/lib/glimmer/swt/widget_proxy.rb:1145:in `block in property_type_converters'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.21.2.1/lib/glimmer/swt/widget_proxy.rb:1033:in `apply_property_type_converters'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.21.2.1/lib/glimmer/swt/widget_proxy.rb:255:in `block in set_attribute'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.21.2.1/lib/glimmer/swt/display_proxy.rb:151:in `auto_exec'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.21.2.1/lib/glimmer/swt/widget_proxy.rb:608:in `auto_exec'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.21.2.1/lib/glimmer/swt/widget_proxy.rb:254:in `set_attribute'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.21.2.1/lib/glimmer/dsl/swt/property_expression.rb:40:in `interpret'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-2.4.1/lib/glimmer/dsl/engine.rb:181:in `block in interpret_expression'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-2.4.1/lib/glimmer/dsl/expression.rb:64:in `around'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-2.4.1/lib/glimmer/dsl/engine.rb:180:in `interpret_expression'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-2.4.1/lib/glimmer/dsl/engine.rb:175:in `interpret'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-2.4.1/lib/glimmer/dsl/engine.rb:48:in `block in Engine'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-cw-video-1.1.0/lib/views/glimmer/video.rb:31:in `block in Video'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-2.4.1/lib/glimmer/dsl/parent_expression.rb:32:in `add_content'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.21.2.1/lib/glimmer/dsl/swt/widget_expression.rb:51:in `add_content'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-2.4.1/lib/glimmer/dsl/engine.rb:199:in `add_content'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-2.4.1/lib/glimmer/dsl/engine.rb:182:in `block in interpret_expression'
	from org/jruby/RubyKernel.java:2019:in `tap'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-2.4.1/lib/glimmer/dsl/engine.rb:181:in `block in interpret_expression'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-2.4.1/lib/glimmer/dsl/expression.rb:64:in `around'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-2.4.1/lib/glimmer/dsl/engine.rb:180:in `interpret_expression'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-2.4.1/lib/glimmer/dsl/engine.rb:175:in `interpret'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-2.4.1/lib/glimmer.rb:78:in `method_missing'
	from /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-cw-video-1.1.0/lib/views/glimmer/video.rb:30:in `block in Video'
```

Somewhere down there is another exception:
```
NoMethodError: undefined method `swt_widget' for true:TrueClass
            initialize at /Users/phuongnd08/.asdf/installs/ruby/jruby-9.4.2.0/lib/ruby/gems/shared/gems/glimmer-dsl-swt-4.21.2.1/lib/glimmer/ui/custom_widget.rb:184
                   new at org/jruby/RubyClass.java:931
```

**Comment by AndyObtiva** [comment] 2023-06-15 19:10
Hi, 

Thank you for reporting. I confirmed the issue and it is caused by a new feature that got added to glimmer-dsl-xml, called xml_attribute_underscore, which conflicted with glimmer-dsl-swt. The issue escaped me in the past because it only happens when I use both libraries at the same time, which is done in glimmer-cw-video. 

In any case, the issue is fixed in glimmer-cw-video version 1.1.1:
https://rubygems.org/gems/glimmer-cw-video/versions/1.1.1

I am closing this issue as a result, but if you have further inquiries, feel free to respond to the issue. I will see them even if the issue is closed.

Cheers,

Andy

**Closed as completed by AndyObtiva** 2023-06-15 19:10 UTC
